name: terraform-ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Architecture Check
        run: bash ./scripts/architecture-check.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.5

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Terraform init core
        working-directory: live/dev
        run: terraform init -backend-config=backend.dev.hcl

      - name: Terraform validate
        working-directory: live/dev
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        working-directory: live/dev
        run: tflint --init && tflint

      - name: Terraform plan
        working-directory: live/dev
        run: terraform plan -lock=false -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: live/dev/tfplan
